name: pytorch
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - flask=1.1.2
  - numpy=1.18.5
  - pip=20.1.1
  - python=3.6.10
  - pytorch=1.5.1
  - requests=2.24.0
  - setuptools
  - torchvision=0.6.1
  - tqdm=4.47.0
  - pip:
    - gunicorn
    - opencv-python